plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 21

Metrics/MethodLength:
  Max: 21

Rails/Exit:
  Exclude:
    - 'spec/**/*'

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# RSpec tweaks
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 8
