plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'db/seeds.rb'

Metrics/AbcSize:
  Max: 22
  Exclude:
    - 'scripts/**/*'

Metrics/ClassLength:
  Exclude:
    - 'scripts/**/*'

Metrics/MethodLength:
  Max: 21
  Exclude:
    - 'scripts/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'scripts/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'scripts/**/*'

Rails/Exit:
  Exclude:
    - 'spec/**/*'
    - 'scripts/**/*'

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# RSpec tweaks
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 8

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
    - 'scripts/**/*'

Rails/EagerEvaluationLogMessage:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'db/seeds.rb'
    - 'scripts/**/*'
